#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-LMSolve
version:      0.7.10
version_from: lib/Games/LMSolve/Base.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_08
